name: CI

on:
  push:
    paths-ignore:
      - '.gitattributes'
      - '.github/*'
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.gitattributes'
      - '.github/*'
      - '.gitignore'
      - 'README.md'

jobs:
  Build:
    name: Build (${{ matrix.Configuration }})
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Release, Debug]
    steps:
      - name: Checkout SPT
        uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init -j $env:NUMBER_OF_PROCESSORS SPTLib
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -A Win32 -DCMAKE_BUILD_TYPE=${{matrix.Configuration}} 
      - name: Build
        run: cmake --build ${{github.workspace}}/build -j $env:NUMBER_OF_PROCESSORS --config ${{matrix.Configuration}}
      - uses: actions/upload-artifact@v4
        with:
          name: spt.dll (${{matrix.Configuration}})
          path: ${{github.workspace}}/build/${{matrix.Configuration}}/spt.dll
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: spt-2013.dll (${{matrix.Configuration}})
          path: ${{github.workspace}}/build/${{matrix.Configuration}}/spt-2013.dll
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: spt-oe.dll (${{matrix.Configuration}})
          path: ${{github.workspace}}/build/${{matrix.Configuration}}/spt-oe.dll
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: spt-bms.dll (${{matrix.Configuration}})
          path: ${{github.workspace}}/build/${{matrix.Configuration}}/spt-bms.dll
          if-no-files-found: error
